[package]
name = "ribidi"
version = "0.1.0"
authors = ["Ella-0 <23418164+Ella-0@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
unicode-bidi = "*"
